apiVersion: v2
name: cubel-cloud
description: A Helm chart for deploying an application with PostgreSQL database
type: application
version: 0.1.2
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "16.7.27"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
