apiVersion: v2
name: cubel-cloud
description: A Helm chart for deploying the homepage application with PostgreSQL database
type: application
version: 0.2.0
appVersion: "0.2.0"

dependencies:
  - name: postgresql
    version: "16.7.27"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
