apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.additionalPort }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
